name: Build Citron (Stable)
concurrency:
  group: build-stable-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 7 1/21 * *"
  workflow_dispatch: {}

jobs:
  build:
    name: "${{ matrix.name }}"
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        include:
          - name: "Citron Build (Normal x86_64)"
            arch_suffix: ""
            build_arg: ""
          - name: "Citron Build (Optimized x86_64)"
            arch_suffix: "_v3"
            build_arg: "v3"
          - name: "Citron Build (Normal PGO x86_64)"
            arch_suffix: "_pgo"
            build_arg: "pgo"
          - name: "Citron Build (Optimized PGO x86_64)"
            arch_suffix: "_v3_pgo"
            build_arg: "v3-pgo"

    container: ghcr.io/pkgforge-dev/archlinux:latest

    steps:
      - name: Install Git
        run: pacman -Syu --noconfirm --needed git

      - name: Cache Pacman packages
        uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: ${{ runner.os }}-pacman-${{ hashFiles('**/get-dependencies.sh') }}
          restore-keys: |
            ${{ runner.os }}-pacman-

      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: 'recursive'

      - name: Install dependencies
        run: chmod +x ./get-dependencies.sh && ./get-dependencies.sh

      - name: Build Citron from source
        run: |
          NPROC_VAL=$(nproc --all)
          JOBS_VAL=$((NPROC_VAL > 4 ? 4 : NPROC_VAL))
          chmod +x ./build-citron.sh
          JOBS=${JOBS_VAL} ./build-citron.sh ${{ matrix.build_arg }}

      - name: Package AppImage
        run: |
          chmod +x ./package-citron.sh
          ARCH_SUFFIX=${{ matrix.arch_suffix }} ./package-citron.sh

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: AppImage${{ matrix.arch_suffix }}
          path: "dist/*.AppImage*"

      - name: Upload version file
        if: ${{ matrix.build_arg == '' }}
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: "dist/version"

  release:
    if: ${{ github.ref_name == 'main' }}
    name: "Release"
    needs: [build]
    permissions:
      actions: read
      security-events: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: AppImage*
          merge-multiple: true
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: version
          path: .
      - name: Read version and Get date
        run: |
          echo "VERSION=$(cat version)" >> "${GITHUB_ENV}"
          echo "DATE=$(date +'%Y-%m-%d_%s')" >> "${GITHUB_ENV}"
      - name: Check files before release
        run: ls -R
      - name: Release Artifacts
        uses: softprops/action-gh-release@v2
        with:
          name: "Citron: ${{ env.VERSION }}"
          tag_name: "${{ env.VERSION }}@${{ env.DATE }}"
          prerelease: false
          draft: false
          generate_release_notes: false
          make_latest: true
          files: |
            *.AppImage*
            *.tar.zst
      - uses: actions/checkout@v4
      - name: Update LATEST_VERSION
        run: |
          echo "${{ env.VERSION }}" > ./LATEST_VERSION
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./LATEST_VERSION
          git commit --allow-empty -m 'bump `LATEST_VERSION` [skip ci]'
          git push
